[package]
name = "rusted-phone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[env]
RUST_LOG = "trace"

[dependencies]
log = "0.4.14"
log-panics = "2.0.0"
simple_logger = "2.1.0"
